// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anbfqhjrfcxhddvgwagy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuYmZxaGpyZmN4aGRkdmd3YWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTY5NDMsImV4cCI6MjA2NjU5Mjk0M30.KElKku-2tKU-bGhwVBW4aZKCIFu5wh5xRPz9fLov9vI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);